url: https://servelproject.github.io
baseurl: 

# Site settings
title: SERVEL Project
email: servelproject@gmail.com
description: "Assurez la réussite de votre oeuvre audiovisuelle en travaillant avec servel."

# Team names, titles and social links
people:
- name: Antonin Servouse
  pic: 1
  position: project's holder
  description: Antonin is passionate about video games, interactive media and cinema. He has three years of experience as financial analyst and ideal skills to run a business, ensure company viability and rise new financing.
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: https://fr.linkedin.com/in/antonin-servouse-156755b0

- name: Romain Trachel
  pic: 2
  position: project's holder
  description: Romain is passionate about science, innovation and new technologies. He has six years of experience in computer science, neuroscience and ideal aptitudes to develop a startup and find new solutions.
  social:
    - title: github
      url: https://github.com/trachelr
    - title: linkedin
      url: https://fr.linkedin.com/in/trachelr


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: http://facebook.com
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: INRIA - Sophia Antipolis/Méditerranée
  - line: 2004 Route des Lucioles, 06902 Valbonne

# Build settings
markdown: kramdown
permalink: pretty
