url: https://servelproject.github.io
baseurl: 

# Site settings
title: SERVEL Project
email: servelproject@gmail.com
description: "Assurez la réussite de votre oeuvre audiovisuelle en travaillant avec servel."


# Team names, titles and social links
people:
- name: Antonin Servouse
  pic: 1
  position: Porteur du projet
  description: three years of experience in the financial field .  Well profile to run a business , to ensure company financial viability and find new financing. Antonin is passionate about video games and movies.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Romain Trachel
  pic: 2
  position: Porteur du projet
  description: six years of experience in the interfaces brain - computer , visual and auditory attention. Ideal profile for developing a technological startup . Roman is passionate about science, innovation and new technologies.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: http://facebook.com
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: INRIA - Sophia Antipolis/Méditerranée
  - line: 2004 Route des Lucioles, 06902 Valbonne

# Build settings
markdown: kramdown
permalink: pretty
